name: Show container platforms

on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx1
        uses: docker/setup-buildx-action@v1

      - name: Show platforms with buildx only
        run: |
          echo "Platforms: ${{ steps.buildx1.outputs.platforms }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx again
        id: buildx2
        uses: docker/setup-buildx-action@v1

      - name: Show platforms with qemu
        run: |
          echo "Platforms: ${{ steps.buildx2.outputs.platforms }}"
